flask_app/views/books.py
from datetime import date
from flask import render_template, request, redirect, url_for, abort
from flask import Blueprint
from flask_login import current_user
from sqlalchemy import select

from ..db import db
from ..models import Book

module = Blueprint("books", __name__)

@module.route("/books", methods=['GET'])
def books_get():
    books = db.session.scalars(select(Book))
    return render_template('books.html', books=books, currect_user=current_user)

@module.route("/books/<book_id>/delete", methods=['POST'])
def books_delete(book_id):
    book = db.session.scalar(select(Book).where(Book.id == book_id))
    if book:
        db.session.delete(book)
        db.session.commit()
    return redirect(url_for(".books_get"))

@module.route("/create", methods=["POST"])
def book_create():
    book_name = request.form["book_name"]
    book_author = request.form["book_author"]
    book_isbn = request.form["book_isbn"]

    new_book = Book(
        title=book_name,
        authors=book_author,
        isbn=book_isbn  
    )
    db.session.add(new_book)
    db.session.commit()

    return redirect(url_for(".books_get"))

@module.route("/books/<book_id>", methods=["GET"])
def book_detail(book_id: int):
    book = db.session.scalar(select(Book).where(Book.id == book_id))
    if book == None:
        abort(404)

    return render_template("book_detail.html", book=book)

@module.route("/editBook", methods=["POST"])
def book_edit():
    book_id = request.form["id"]
    book = db.session.scalar(select(Book).where(Book.id == book_id))
    if book == None:
        abort(404)

    for key, value in request.form.items():
        if key == "id":
            book.id = value
        elif key == "title":
            book.title = value
        elif key == "authors":
            book.authors = value
        elif key == "isbn":
            book.isbn = value
        elif key == "publisher":
            book.publisher = value
        elif key == "published_date":
            book.published_date = date.fromisoformat(value) if value else None

    db.session.commit()

    return redirect(url_for(".book_detail", book_id=book_id))

flask_app/views/borrow.py
from datetime import date, datetime, timedelta
from dataclasses import dataclass

from flask import render_template, request, redirect, url_for, abort, Response
from flask import Blueprint
from flask_login import login_required, current_user
from sqlalchemy import select
from sqlalchemy.orm import joinedload

from ..db import db
from ..models import Book, Borrow, User, AcceptWait

module = Blueprint("borrow", __name__)

@module.route("/borrow/<book_id>", methods=['GET'])
@login_required
def borrow_get(book_id: str):
    book = db.session.scalar(select(Book).where(Book.id==book_id))
    if not book:
        abort(404)

    return_exptected_at = date.today() + timedelta(days=7)
    current_borrow = db.session.scalar(select(Borrow).where(Borrow.book_id==book_id).where(Borrow.returned_at==None))
    return render_template("borrow.html", 
                           book=book,
                           current_borrow=current_borrow, 
                           return_exptected_at=return_exptected_at)

@module.route("/borrows", methods=['GET'])
@login_required
def borrows_get():
    borrows = db.session.scalars(
        select(Borrow)
        .where(Borrow.user_id==current_user.id)
        .where(Borrow.returned_at==None)
        .options(joinedload(Borrow.book))
    )
    return render_template("borrows.html", borrows=borrows)

@module.route("/borrow/<book_id>", methods=['POST'])
@login_required
def borrow_post(book_id: str):
    book = db.session.scalar(select(Book).where(Book.id==book_id))
    if not book:
        abort(404)

    current_borrow = db.session.scalar(select(Borrow).where(Borrow.book_id==book_id).where(Borrow.returned_at==None))
    if current_borrow:
        # 借りられているなら400
        abort(400)

    accept_wait = AcceptWait(
        will_cancel_at=datetime.now() + timedelta(hours=1)
    )

    borrow = Borrow(
        user_id=current_user.id,
        book_id=book.id,
        return_expected_at=date.today() + timedelta(days=7),
        borrowed_at=date.today(),
        accept_wait=accept_wait
    )

    db.session.add(borrow)
    db.session.add(accept_wait)
    db.session.commit()

    return redirect(url_for(".borrows_get"))

@module.route("/return/<book_id>", methods=['POST'])
@login_required
def return_post(book_id: str):
    book = db.session.scalar(select(Book).where(Book.id==book_id))
    if not book:
        abort(404)
    
    current_borrow = db.session.scalar(select(Borrow).where(Borrow.book_id==book_id).where(Borrow.returned_at==None))
    if (
        not current_borrow or 
        current_borrow.user_id != current_user.id or
        current_borrow.accept_wait and not current_borrow.accept_wait.is_accepted
    ):
        abort(400)
    
    current_borrow.returned_at = date.today()
    db.session.commit()

    return redirect(url_for(".borrows_get"))

@module.route("/accept")
def accept_get():
    waits = db.session.scalars(
        select(AcceptWait)
        .where(AcceptWait.is_accepted == False)
        .options(joinedload(AcceptWait.borrow))
    )

    if len(request.args.keys()) == 0:
        return render_template("accept.html", waits=waits) 
    
    is_accept = bool(request.args.get("is_accept"))
    accept_id = request.args.get("accept_id")

    wait = db.session.scalar(
        select(AcceptWait)
        .where(AcceptWait.id == accept_id)
        .options(joinedload(AcceptWait.borrow))
    )

    if wait and not wait.is_accepted:
        if is_accept:
            wait.is_accepted = True
        else:
            db.session.delete(wait)
            db.session.delete(wait.borrow)

        db.session.commit()

    res = Response(status=302)
    res.location = request.path
    res.headers["X-Debug"] = str(wait.borrow)
    return res
        



@module.route("/history", methods=['GET'])
def history_get():
    borrows = db.session.scalars(
        select(Borrow)
        .where(Borrow.user_id==current_user.id)
        .options(joinedload(Borrow.book))
    )
    return render_template("history.html", borrows = borrows)

flask_app/views/login.py
from flask import render_template, request, redirect, url_for, flash
from flask import Blueprint
from flask_login import current_user, login_user, logout_user, login_required
from sqlalchemy import select

from ..db import db
from ..models import User

module = Blueprint("login", __name__)

@module.route("/login", methods=['GET'])
def login_get():
    return render_template("login.html", callback=request.args.get("callback"))

@module.route("/signup", methods=["GET"])
def signup_get():
    return render_template("signup.html", callback=request.args.get("callback"))

@module.route("/login", methods=["POST"])
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")
    callback = request.args.get("callback")

    user = db.session.scalar(select(User).where(User.email==email))
    if not user or not user.check_password(password):
        return redirect(url_for(".login_get"))
    
    login_user(user)
    if callback:
        return redirect(callback)
    return redirect(url_for("index.index_get"))

@module.route("/signup", methods=["POST"])
def signup_post():
    email = request.form.get("email")
    password = request.form.get("password")
    callback = request.args.get("callback")

    # TODO: 存在するユーザの場合の処理
    existing_user = db.session.scalar(select(User).where(User.email==email))
    if existing_user:
        return redirect(url_for(".signup_get"))
    
    user = User(name=email + "さん", email=email)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()
    
    login_user(user)
    if callback:
        return redirect(callback)
    return redirect(url_for("index.index_get"))

@module.route("/logout", methods=["GET"])
def logout_get():
    logout_user()
    return redirect(url_for(".login_get"))

flask_app/views/qr.py
from flask import render_template, request, redirect, url_for
from flask import Blueprint
from sqlalchemy import select

from ..db import db
from ..models import Book

module = Blueprint("qr", __name__)

@module.route("/qr", methods=['GET'])
def books_get():
    return "このページは" + module.name + "です"

@module.route("/qr/<book_id>", methods=["GET"])
def qr_get(book_id: str):
    url_borrow = url_for("borrow.borrow_get", book_id=book_id)
    return render_template("qr.html", url_path=url_borrow)

flask_app/templates/accept.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>了承待ち一覧</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    {% include "header.html" %}

    <div class="container py-5">
        <h2 class="mb-4">了承待ち一覧</h2>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>ユーザー</th>
                    <th>書籍</th>
                    <th>承認期限</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for wait in waits %}
                    <tr>
                        <td>{{ wait.borrow.user.name }}</td>
                        <td>{{ wait.borrow.book.title }}</td>
                        <td>{{ wait.will_cancel_at.strftime('%Y-%m-%d') }}</td>
                        <td>
                            <button type="submit" class="btn btn-primary btn-sm" onclick="location.href=`?is_accept=1&accept_id={{ wait.id }}`"
                            >承認</button>
                            <button type="submit" class="btn btn-danger btn-sm" onclick="location.href=`?is_accept=&accept_id={{ wait.id }}`"
                            >拒否</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

flask_app/templates/book_detail.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>詳細 | {{ book.title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

    {% include "header.html" %}

    <div class="container py-5">
        <h1 class="h2">詳細: {{ book.title }}</h1>
        <div class="container py-2">
            <a href="{{ url_for('qr.qr_get', book_id=book.id) }}">
                <button class="btn btn-primary">貸出QR</button>
            </a>
            <form action="{{ url_for('books.books_delete', book_id=book.id) }}" method="post">
                <button type="submit" class="btn btn-danger">削除</button>
            </form>
        </div>
        <form id="form_edit" target="_self" action="/editBook" method="post" class="row g-3">
            <div class="col-12">
                <label for="title" class="form-label">書籍名</label>
                <input id="title" name="title" type="text" class="form-control" value="{{ book.title }}" />
            </div>
            <div class="col-12">
                <label for="authors" class="form-label">著者</label>
                <input id="authors" name="authors" type="text" class="form-control" value="{{ book.authors or "" }}" />
            </div>
            <div class="col-12">
                <label for="isbn" class="form-label">ISBN</label>
                <input id="isbn" name="isbn" type="text" class="form-control" value="{{ book.isbn or "" }}" />
            </div>
            <div class="col-12">
                <label for="publisher" class="form-label">出版社</label>
                <input id="publisher" name="publisher" type="text" class="form-control" value="{{ book.publisher or "" }}" />
            </div>
            <div class="col-12">
                <label for="published_date" class="form-label">出版日</label>
                <input id="published_date" name="published_date" type="text" class="form-control" value="{{ book.published_date or "" }}" />
            </div>
            <div class="col-12 d-flex justify-content-between">
                <input type="submit" value="変更を反映する" class="btn btn-success" />
                <input name="id" type="hidden" value="{{ book.id }}" />
            </div>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>

</html>

flask_app/templates/books.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>書籍管理アプリ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    {% include "header.html" %}

    <div class="container py-5">
        <!-- 書籍一覧テーブル -->
        <h2 class="mb-4">書籍一覧</h3>
        <table class="table table-striped table-bordered mb-5">
            <thead>
                <tr>
                    <th scope="col">書籍名</th>
                    <th scope="col">著者</th>
                    <th scope="col">ISBN</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                <tr>
                    <td>
                        <a href="books/{{ book.id }}" class="text-decoration-none">{{ book.title }}</a>
                    </td>
                    <td>{{ book.authors }}</td>
                    <td>{{ book.isbn }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- 書籍追加フォーム -->
        <div class="card shadow">
            <div class="card-header text-center">
                <h3>新しい書籍を追加</h3>
            </div>
            <div class="card-body">
                <form id="form_create" action="create" method="post">
                    <div class="mb-3">
                        <label for="book_name" class="form-label">書籍名</label>
                        <input type="text" class="form-control" id="book_name" name="book_name" placeholder="書籍名を入力してください" required>
                    </div>
                    <div class="mb-3">
                        <label for="book_author" class="form-label">著者</label>
                        <input type="text" class="form-control" id="book_author" name="book_author" placeholder="著者名を入力してください" required>
                    </div>
                    <div class="mb-3">
                        <label for="book_isbn" class="form-label">ISBN</label>
                        <input type="text" class="form-control" id="book_isbn" name="book_isbn" placeholder="ISBNを入力してください" required>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">追加</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

flask_app/templates/borrow.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ book.title }} - 詳細</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    {% include "header.html" %}

    <div class="container py-5">
        <div class="card shadow-sm">
            <div class="card-header text-center">
                <h4>{{ book.title }}</h4>
            </div>
            <div class="card-body">
                <p class="lead"><strong>著者:</strong> {{ book.authors }}</p>
                {% if current_borrow == None %}
                    <p><strong>返却予定日:</strong> {{ return_exptected_at.strftime('%Y-%m-%d') }}</p>
                    <form action="{{ url_for('borrow.borrow_post', book_id=book.id) }}" method="post">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">借りる</button>
                    </form>
                {% elif current_borrow.user_id == current_user.id %}
                    {% if current_borrow.accept_wait.is_accepted %}
                        <p><strong>返却予定日:</strong> {{ current_borrow.return_expected_at.strftime('%Y-%m-%d') }}</p>
                        <form action="{{ url_for('borrow.return_post', book_id=book.id) }}" method="post">
                            <button type="submit" class="btn btn-danger btn-lg btn-block">返却する</button>
                        </form>
                    {% else %}
                        <p><strong>返却予定日:</strong> {{ current_borrow.return_expected_at.strftime('%Y-%m-%d') }}</p>
                        <form action="{{ url_for('borrow.return_post', book_id=book.id) }}" method="post">
                            <button type="submit" class="btn btn-danger btn-lg btn-block disabled">返却する</button>
                            <span>承認待ち</span>
                        </form>
                    {% endif %}
                {% else %}
                    <p><strong>返却予定日:</strong> {{ current_borrow.return_expected_at.strftime('%Y-%m-%d') }}</p>
                    <div class="alert alert-warning" role="alert">
                        この本は現在借りられません。
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

flask_app/templates/borrows.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>借りている本一覧</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    {% include "header.html" %}

    <div class="container py-5">
        <h2 class="mb-4">借りている本一覧</h2>
        
        {% if borrows %}
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>書籍名</th>
                        <th>著者</th>
                        <th>返却予定日</th>
                        <th>返却</th>
                    </tr>
                </thead>
                <tbody>
                    {% for borrow in borrows %}
                        <tr>
                            <td>{{ borrow.book.title }}</td>
                            <td>{{ borrow.book.authors }}</td>
                            <td>{{ borrow.return_expected_at.strftime('%Y-%m-%d') }}</td>
                            <td>
                                {% if borrow.accept_wait.is_accepted %}
                                    <button type="submit" class="btn btn-danger btn-sm" onclick="location.href=`{{ url_for('borrow.borrow_get', book_id=borrow.book.id) }}`"
                                    >返却する</button>
                                {% else %}
                                    承認待ちです
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info" role="alert">
                現在借りている本はありません。
            </div>
        {% endif %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

flask_app/templates/header.html
<header class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">書籍管理</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link">{{ current_user.name }}</a>
                </li>
                <li class="nav-item me-5">
                    <a class="nav-link" href="{{ url_for('login.logout_get') }}">ログアウト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('borrow.borrows_get') }}">借りている本</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('books.books_get') }}">本管理</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('borrow.history_get') }}">貸出履歴</a>
                </li>
            </ul>
        </div>
    </div>
</header>

flask_app/templates/history.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>書籍管理アプリ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    {% include "header.html" %}

    <div class="container py-5">
        <!-- 書籍一覧テーブル -->
        <h2 class="mb-4">貸し出し履歴</h3>
        <table class="table table-striped table-bordered mb-5">
            <thead>
                <tr>
                    <th scope="col">書籍名</th>
                    <th scope="col">貸し出し日</th>
                    <th scope="col">返却日</th>
                </tr>
            </thead>
            <tbody>
                {% for borrow in borrows %}
                <tr>
                    <td>
                        {{borrow.book.title}}
                    </td>
                    <td>{{ borrow.borrowed_at}}</td>
                    <td>{{ borrow.returned_at }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

flask_app/templates/index.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>書籍管理アプリ</title>
</head>


<body>
    <h1>これは書籍管理アプリです</h1>
</body>

flask_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログイン</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card p-4 shadow" style="width: 100%; max-width: 600px;">
            <h1 class="text-center mb-4">知識への扉を開く・・・</h1>
            <form method="POST" action="{{ url_for('login.login_post', callback=callback) }}">
                <div class="mb-3">
                    <label for="email" class="form-label">メールアドレス</label>
                    <input type="text" class="form-control" id="email" name="email" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">パスワード</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">ログイン</button>
            </form>
            <p class="text-center mt-3">アカウントをまだ作っていないなら<a href="{{ url_for('login.signup_get', callback=callback) }}">登録</a>してください</p>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

flask_app/templates/qr.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QRコード生成</title>
    <script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 50px;
        }
        input {
            padding: 10px;
            width: 80%;
            margin-bottom: 20px;
            font-size: 16px;
        }
        canvas {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>貸出用QRコード</h1>
    <canvas class="qrcode" data-size="10"></canvas>
    <canvas class="qrcode" data-size="15"></canvas>
    <canvas class="qrcode" data-size="20"></canvas>
    <canvas class="qrcode" data-size="25"></canvas>
    <canvas class="qrcode" data-size="30"></canvas>
    <canvas class="qrcode" data-size="40"></canvas>
    <canvas class="qrcode" data-size="50"></canvas>

    <script>
        function generateQRCode(outputCanvas, data, resolution) {
            if (data.trim()) {
                QRCode.toCanvas(outputCanvas, data, { width: resolution }, function (error) {
                    if (error) console.error(error);
                });
            }
        }

        const path = "{{ url_path }}"
        const url = "http://" + document.location.host + path
        const qrcode_outputs = document.getElementsByClassName("qrcode")
        for(var i = 0; i < qrcode_outputs.length; i++) {
            canvas = qrcode_outputs[i]
            size = canvas.dataset.size
            generateQRCode(canvas, url, 10 * size)
            canvas.style["width"] = size + "mm"
            canvas.style["height"] = size + "mm"
        }
    </script>
</body>
</html>

flask_app/templates/quagga.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>書籍管理アプリ</title>
</head>


<body>
    <script src="https://cdn.jsdelivr.net/npm/quagga@0.12.1/dist/quagga.min.js"></script>

    <!-- {% if current_user.is_authenticated %}
        <a>ログインしていません</a>
    {% else %}
        <a>ログインしています</a>
    {% endif %} -->
    <h1>これは書籍管理アプリです</h1>
    <div id="cameraDisplay"></div>

    <script>
        const onProcessed = (callback) => {
            if(callback) {
                console.log(callback)
            }
        }

        Quagga.init({
            inputStream : {
              name : "Live",
              type : "LiveStream",
              target: document.querySelector('#cameraDisplay')    // Or '#yourElement' (optional)
            },
            decoder : {
              readers : ["code_128_reader"]
            }
          }, function(err) {
              if (err) {
                  console.log(err);
                  return
              }
              console.log("Initialization finished. Ready to start");
              Quagga.onDetected(onProcessed)
              Quagga.start();
          });
    </script>
</body>

flask_app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card p-4 shadow" style="width: 100%; max-width: 600px;">
            <h1 class="text-center text-nonwrap mb-4">アカウント登録</h1>
            <form method="POST" action="{{ url_for('login.signup_post', callback=callback) }}">
                <div class="mb-3">
                    <label for="email" class="form-label">メールアドレス</label>
                    <input type="text" class="form-control" id="email" name="email" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">パスワード</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">登録する</button>
            </form>
            <p class="text-center mt-3">アカウントをすでに持っているなら<a href="{{ url_for('login.login_get', callback=callback) }}">ログイン</a>してください</p>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>